# This Dockerfile was helpful for building and packaging dlsh.
# Docker gives a clean environment, meaning the steps below must account for all dependencies.
# Docker also gives us a local environment that's easy to iterate on.
# Getting this working was the basis for the automated CI builds, over in .github/workflows/.
#
# To run this docker build cd to the dlsh repo root and:
#
#   docker build . -f scripts/docker/Dockerfile-build -t dlsh-build:local
#
# To sanity check the libs and headers that are ready for packaging:
#
#   docker run --rm -ti dlsh-build:local dpkg-deb --info dlsh_0.0.0_amd64.deb
#   docker run --rm -ti dlsh-build:local dpkg-deb --contents  dlsh_0.0.0_amd64.deb


# Start with a fresh Ubuntu environment.
FROM ubuntu:22.04

# Set up a dev tools and dlsh build dependencies.
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt update \
    && apt install --no-install-recommends --yes ca-certificates build-essential cmake zlib1g-dev liblz4-dev \
    && apt-get clean \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

# Add this repo and submodules.
ADD . /work/dlsh/

# Install TCL 9 to the build environment.
WORKDIR /work/dlsh/deps/tcl/unix/
RUN ./configure \
  && make \
  && make install

# Install the Jansson JSON dependency.
WORKDIR /work/dlsh/deps/jansson/
RUN cmake -B build \
  && cmake --build build \
  && cmake --install build

# Install the libharu PDF dependency -- both static and dynamic builds.
WORKDIR /work/dlsh/deps/libharu/
RUN cmake -DBUILD_SHARED_LIBS=OFF -B build \
  && cmake --build build \
  && cmake --install build \
  && cmake -DBUILD_SHARED_LIBS=ON -B build \
  && cmake --build build \
  && cmake --install build

# Build dlsh itself and install to a packaging dir.
ADD . /work/dlsh/
WORKDIR /work/dlsh/
RUN cmake -D PROJECT_VERSION=0.0.0 -B build \
  && cmake --build build \
  && cpack -G DEB --config build/CPackConfig.cmake
