# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded dlsh 1.2 [list set dlsh_library [file join $dir]]\n[list load [file join $dir $::tcl_platform(os) $::tcl_platform(machine) libdlsh[info sharedlibextension]]]\n[list source [file join $dir dlbasic.tcl]]\n[list source [file join $dir dlcompat.tcl]]\n[list source [file join $dir dlinput.tcl]]\n[list source [file join $dir dlmodules.tcl]]\n[list source [file join $dir dlsort.tcl]]\n[list source [file join $dir dmbasic.tcl]]\n[list source [file join $dir events.tcl]]\n[list source [file join $dir fitfuncs.tcl]]\n[list source [file join $dir plot.tcl]]\n[list source [file join $dir regress.tcl]]\n[list source [file join $dir stats.tcl]]\n[list source [file join $dir dlshrc]]
